### ISSUE TITLE
Retain comments in .vscode/settings.json

### ISSUE THREAD

**Issue by jibbers42** [leoafarias/fvm#642] opened 2024-02-22 02:13 UTC
**Is your feature request related to a problem? Please describe.**
`fvm use` removes comments from `.vscode/settings.json`.

**Describe the solution you'd like**
I'd like comments retained. I'm unsure of what all fvm may need to write in settings, but it would be nice if it could only modify the required lines, such as the value for key `dart.flutterSdkPath` (or of course adding the line it if it doesn't exist).

**Comment by leoafarias** [comment] 2024-02-22 16:15
@jibbers42 this is a duplicate of #635

Comments are not part of the JSON specification. Therefore, it will not be supported. However, if you choose to comment, I suggest doing the following:

```json
{
    "_comment": "This is the basic data",
    "key": "value"
}
```

This would allow valid comments with json

**Closed by leoafarias** 2024-02-22 16:15 UTC
Labels: enhancement

**Comment by jibbers42** [comment] 2024-02-22 19:38
Oops, I forgot to search. Thanks for the workaround.

**Comment by okaxaki** [comment] 2024-11-30 03:14
The VS Code configuration files have a .json extension (probably for simplicity or historical reasons), but internally, they are read and written as JSONC. Therefore it would be greatly appreciated if they could be handled as JSONC.
