### ISSUE TITLE
[BUG] Fvm flutter build apk --release is downloading flutter again

### ISSUE THREAD

**Issue by AliYar-Khan** [leoafarias/fvm#790] opened 2024-11-02 14:05 UTC
**Before creating a bug report please make check the following**

- [X] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [X If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [X] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [X] Run `fvm doctor` if possible and add the output to the issue.

### fvm doctor ouptput
```
FVM Doctor:
------------------------------------------------------------------------------------------------------------------------------------------------------------Project:
┌─────────────────────────────┬──────────────────────┐
│ Project                     │ toolivo              │
├─────────────────────────────┼──────────────────────┤
│ Directory                   │ C:\Freelance\toolivo │
├─────────────────────────────┼──────────────────────┤
│ Active Flavor               │ None                 │
├─────────────────────────────┼──────────────────────┤
│ Is Flutter Project          │ Yes                  │
├─────────────────────────────┼──────────────────────┤
│ Dart Tool Generator Version │ 3.4.1                │
├─────────────────────────────┼──────────────────────┤
│ Dart tool version           │ 3.22.1               │
├─────────────────────────────┼──────────────────────┤
│ .gitignore Present          │ Yes                  │
├─────────────────────────────┼──────────────────────┤
│ Config Present              │ Yes                  │
├─────────────────────────────┼──────────────────────┤
│ Pinned Version              │ 3.22.1               │
├─────────────────────────────┼──────────────────────┤
│ Config path                 │ .fvmrc               │
├─────────────────────────────┼──────────────────────┤
│ Local cache dir             │ .fvm\versions        │
├─────────────────────────────┼──────────────────────┤
│ Version symlink             │ .fvm\versions\3.22.1 │
└─────────────────────────────┴──────────────────────┘


IDEs:
Cannot resolve symbolic links

Path: C:\Freelance\toolivo\.fvm\versions\3.22.1

Please run command with  --verbose if you want more information
```

**Describe the bug**
version 3.22.1 is already installed but it stills try to download again

**To Reproduce**

**Expected behavior**
It shouldn't redownload the flutter

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

**Desktop (please complete the following information):**

- OS: Windows
- FVM Version 3.2.1
- If Windows: Windows Terminal

**Additional context**

**Comment by AliYar-Khan** [comment] 2024-11-02 16:15
I reinstall fvm using choco. Now gives this error

`Cannot find file at '..\lib\fvm\bin\fvm.exe' (C:\ProgramData\chocolatey\lib\fvm\bin\fvm.exe). This usually indicates a missing or moved file.`

`choco install fvm --force
Chocolatey v2.3.0
Installing the following packages:
fvm
By installing, you accept licenses for the packages.
fvm v3.2.1 already installed. Forcing reinstall of version '3.2.1'.
 Please use upgrade if you meant to upgrade to a new version.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading fvm 3.2.1... 100%

fvm v3.2.1 (forced) [Approved] - Possibly broken
fvm package files install completed. Performing other installation steps.
The package fvm wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): A

Fetching Dart dependencies...
Building executable...
Error: Unable to find git in your PATH.
Added C:\ProgramData\chocolatey\bin\fvm.exe shim pointed to '..\lib\fvm\bin\fvm.exe'.
 The install of fvm was successful.
  Software install location not explicitly set, it could be in package or
  default install location of installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log)`

**Comment by leoafarias** [comment] 2024-11-04 18:31
@AliYar-Khan it seems this is a duplicate of #781, so will be closing

**Closed by leoafarias** 2024-11-04 18:31 UTC
Labels: bug
