### ISSUE TITLE
[BUG] pub: command not found

### ISSUE THREAD

**Issue by lukepighetti** [leoafarias/fvm#287] opened 2021-05-04 15:41 UTC
Now that we typically use `flutter pub` and `dart pub`, is it appropriate to expect `pub` to be available as a command? Should `fvm` use `dart pub` instead?

**Comment by leoafarias** [comment] 2021-05-04 16:02
@lukepighetti Let me know if this is what you are referencing.
https://fvm.app/docs/guides/running_flutter#dart

There are a few use cases for this. Flutter nests some dart commands but also there are some that are only available outside.

So for example, the following will do a pub get using the embedded dart sdk within Flutter.
```
fvm dart pub get
```

**Comment by lukepighetti** [comment] 2021-05-05 11:42
I installed `fvm` and every time I try to use it, it says `pub: command not found`, presumably because it's not on my PATH since `pub` was rolled into `dart pub` as of recent months

**Comment by leoafarias** [comment] 2021-05-05 12:03
@lukepighetti you get this message when trying to run "fvm pub" ?

**Comment by lukepighetti** [comment] 2021-05-05 12:39
```
% fvm
Can't load Kernel binary: Invalid SDK hash.
/Users/lukepighetti/.pub-cache/bin/fvm: line 15: pub: command not found
```

**Comment by leoafarias** [comment] 2021-05-05 13:36
oh ok, this doesn't seem to be an FVM error, as it happens before running FVM.

I would try doing a `dart pub global activate fvm ` again, and/or a `dart pub cache repair`

**Comment by Akaatsukhi** [comment] 2021-05-23 12:58
On linux i am facing  kind a same issue and doing a `dart pub global activate fvm` again, and/or a `dart pub cache repair` does solve the issue but **temprorary**. Coz when i change the global version of flutter  in fvm the error come up the again...it totally frustrating to again & again doing `dart pub global activate fvm`  and `dart pub cache repair`. please help...

```
Can't load Kernel binary: Invalid kernel binary format version.
/home/lazy/.pub-cache/bin/fvm: 15: pub: not found


```

**Comment by leoafarias** [comment] 2021-05-23 13:42
@Akaatsukhi this is not an fvm issue, the issue is with the dependencies snapshot were built with another version of dart. 

The only way to avoid doing doing the cache repair every time is to use fvm per project and try to leave the global version the same.

**Comment by leoafarias** [comment] 2021-05-23 13:42
Also I don’t think this is the issue @lukepighetti is talking about

**Comment by Akaatsukhi** [comment] 2021-05-23 15:23
> @Akaatsukhi this is not an fvm issue, the issue is with the dependencies snapshot were built with another version of dart.
> 
> The only way to avoid doing doing the cache repair every time is to use fvm per project and try to leave the global version the same.

 Also  when i set the global version through Sidekick GUI it doesn't create any problem...But yeah for cli i think i will have to use it per project.

**Comment by leoafarias** [comment] 2021-06-16 16:18
Closing this issue, we have updated the FAQ which maybe this is what its related to, if not feel free to open it again. https://fvm.app/docs/guides/faq#command-pub-not-found

**Closed by leoafarias** 2021-06-16 16:18 UTC
Labels: bug

**Comment by okelloEnos** [comment] 2021-12-13 08:34
/home/okello/.pub-cache/bin/fvm: 8: dart: not found
Doing fvm install version 2.2.5 but i cannot get around this issue ? Need Assistance Kindly

**Comment by leoafarias** [comment] 2021-12-13 13:28
@okelloEnos could open a new issue, and provide `fvm doctor` output please
