### ISSUE TITLE
flutter fvm: Not found: 'package:fvm/src/runner.dart

### ISSUE THREAD

**Issue by tazik561** [leoafarias/fvm#359] opened 2021-11-08 14:52 UTC
I have *macbookpro Monterrey os*.

I am using fvm as  SDK manager . Now I am running flutter pub cache repair I got this error:

    uilt devtools:devtools.
    Installed executable devtools.
    Reactivating fvm 2.2.3...
    Building package executables...
    Failed to build fvm:main:
    Error: Couldn't resolve the package 'fvm' in 'package:fvm/src/runner.dart'.
    ../../../../.pub-cache/hosted/pub.dartlang.org/fvm-2.2.3/bin/main.dart:3:8: Error: Not found: 'package:fvm/src/runner.dart'
    import 'package:fvm/src/runner.dart';
           ^
    ../../../../.pub-cache/hosted/pub.dartlang.org/fvm-2.2.3/bin/main.dart:6:14: Error: Method not found: 'FvmCommandRunner'.
      exit(await FvmCommandRunner().run(args));
                 ^^^^^^^^^^^^^^^^
    Failed to reactivate fvm 2.2.3: Failed to build fvm:main:
    Error: Couldn't resolve the package 'fvm' in 'package:fvm/src/runner.dart'.
    ../../../../.pub-cache/hosted/pub.dartlang.org/fvm-2.2.3/bin/main.dart:3:8: Error: Not found: 'package:fvm/src/runner.dart'
    import 'package:fvm/src/runner.dart';
           ^
    ../../../../.pub-cache/hosted/pub.dartlang.org/fvm-2.2.3/bin/main.dart:6:14: Error: Method not found: 'FvmCommandRunner'.
      exit(await FvmCommandRunner().run(args));
                 ^^^^^^^^^^^^^^^^
    Binstubs exist for non-activated packages:
      From fvm: fvm
    Reactivated 1 package.
    Failed to reactivate 1 package:
    - fvm
    pub finished with exit code 69

This is my version of FVM:

    alt@alts-MacBook-Pro mate-app % fvm --version
    2.2.3

and this project doctor:

    alt@alts-MacBook-Pro mate-app % fvm flutter doctor
    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en)
    [!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
        ✗ cmdline-tools component is missing
          Run `path/to/sdkmanager --install "cmdline-tools;latest"`
          See https://developer.android.com/studio/command-line for more details.
        ✗ Android license status unknown.
          Run `flutter doctor --android-licenses` to accept the SDK licenses.
          See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
    [✓] Xcode - develop for iOS and macOS
    [✓] Chrome - develop for the web
    [✓] Android Studio (version 2020.3)
    [✓] VS Code (version 1.62.0)
    [✓] Connected device (1 available)

This is my .zshrc config file:
```
export ANDROID_HOME=/Users/alt/Mobile/Sdk/Andriod
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$HOME/.pub-cache/bin
export PATH=$PATH:/usr/local/Cellar/dart/2.13.4/bin
export PATH=$PATH:$HOME/fvm/versions/stable/bin
export PATH="$PATH:$HOME/.pub-cache/bin"

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH

export PATH=$PATH:/Applications/"Android Studio.app"
```

This fvm doctor:

```
alt@alts-MacBook-Pro mate-app % fvm doctor

FVM Version: 2.2.3
_________________

FVM config found:
_________________

Project: mate-app
Directory: /Users/alt/Mobile/Projects/Flutter/mate-app
Version: 2.5.3
Project Flavor: None selected
_________________

Version is currently cached locally.

Cache Path: /Users/alt/fvm/versions/2.5.3
Channel: false
SDK Version: 2.5.3

IDE Links
VSCode: .fvm/flutter_sdk
Android Studio: /Users/alt/Mobile/Projects/Flutter/mate-app/.fvm/flutter_sdk


Configured env paths:
_________________

Flutter:
/Users/alt/fvm/versions/stable/bin/flutter

Dart:
/usr/local/Cellar/dart/2.13.4/libexec/bin/dart

FVM_HOME:
not set
```

**Comment by leoafarias** [comment] 2021-11-08 17:13
@tazik561 this seems to be a duplicate of #352. Thank you

**Closed by leoafarias** 2021-11-08 17:13 UTC
Labels: bug
