### ISSUE TITLE
Guide on proper setup on Windows

### ISSUE THREAD

**Issue by DonnC** [leoafarias/fvm#119] opened 2020-08-25 10:11 UTC
i've just started trying out `fvm` i followed how to install fvm using the `pub global` command and i installed it properly but cant do `fvm install <version>` please what am i doing wrong
`..\Pub\Cache\bin`  is in my environment path
![image](https://user-images.githubusercontent.com/47761288/91161815-8ad22980-e6cb-11ea-8188-85c4a1f77ba9.png)
when i run that command, its just creating an empty folder which shows when i run the commands
![image](https://user-images.githubusercontent.com/47761288/91161999-c836b700-e6cb-11ea-83a4-85f4f9f3a167.png)

**Comment by leoafarias** [comment] 2020-08-25 10:34
It seems that this is related to #103 which was confirmed to be fixed. Could you please run the `install` command with the `--verbose` flag.

**Comment by DonnC** [comment] 2020-08-25 12:28
```
1.20.2 exists but was not setup correctly. Doing cleanup...
Installing version: 1.20.2:
$ git clone -c advice.detachedHead=false --progress --single-branch -b 1.20.2 https://github.com/flutter/flutter.git "C:\Users\Donald Chinhuru\fvm\versions\1.20.2"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
[     8.962s] ⚠️  ExceptionCouldNotClone: Could not install Flutter version: 1.20.2.
#0      gitCloneCmd (package:fvm/flutter/flutter_tools.dart:60:5)
<asynchronous suspension>
#1      installRelease (package:fvm/utils/installer.dart:21:9)
#2      InstallCommand.run (package:fvm/commands/install.dart:50:11)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#5      new Future.sync (dart:async/future.dart:223:31)
#6      CommandRunner.run (package:args/command_runner.dart:112:14)
#7      fvmRunner (package:fvm/fvm.dart:27:23)
#8      main (file:///C:/Users/Donald%20Chinhuru/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-1.2.3/bin/main.dart:4:9)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Unhandled exception:
ExceptionCouldNotClone: Could not install Flutter version: 1.20.2.
#0      gitCloneCmd (package:fvm/flutter/flutter_tools.dart:60:5)
<asynchronous suspension>
#1      installRelease (package:fvm/utils/installer.dart:21:9)
#2      InstallCommand.run (package:fvm/commands/install.dart:50:11)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#5      new Future.sync (dart:async/future.dart:223:31)
#6      CommandRunner.run (package:args/command_runner.dart:112:14)
#7      fvmRunner (package:fvm/fvm.dart:27:23)
#8      main (file:///C:/Users/Donald%20Chinhuru/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-1.2.3/bin/main.dart:4:9)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
1.20.2 exists but was not setup correctly. Doing cleanup...
Installing version: 1.20.2:
$ git clone -c advice.detachedHead=false --progress --single-branch -b 1.20.2 https://github.com/flutter/flutter.git "C:\Users\Donald Chinhuru\fvm\versions\1.20.2"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
[     5.702s] ⚠️  ExceptionCouldNotClone: Could not install Flutter version: 1.20.2.
#0      gitCloneCmd (package:fvm/flutter/flutter_tools.dart:60:5)
<asynchronous suspension>
#1      installRelease (package:fvm/utils/installer.dart:21:9)
#2      InstallCommand.run (package:fvm/commands/install.dart:50:11)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#5      new Future.sync (dart:async/future.dart:223:31)
#6      CommandRunner.run (package:args/command_runner.dart:112:14)
#7      fvmRunner (package:fvm/fvm.dart:27:23)
#8      main (file:///C:/Users/Donald%20Chinhuru/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-1.2.3/bin/main.dart:4:9)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Unhandled exception:
ExceptionCouldNotClone: Could not install Flutter version: 1.20.2.
#0      gitCloneCmd (package:fvm/flutter/flutter_tools.dart:60:5)
<asynchronous suspension>
#1      installRelease (package:fvm/utils/installer.dart:21:9)
#2      InstallCommand.run (package:fvm/commands/install.dart:50:11)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#5      new Future.sync (dart:async/future.dart:223:31)
#6      CommandRunner.run (package:args/command_runner.dart:112:14)
#7      fvmRunner (package:fvm/fvm.dart:27:23)
#8      main (file:///C:/Users/Donald%20Chinhuru/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-1.2.3/bin/main.dart:4:9)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by DonnC** [comment] 2020-08-25 12:32
still encountering the same issue even when i try `fvm install 1.17.1` or any other version

**Comment by leoafarias** [comment] 2020-08-25 12:37
@DonnC will run a test on a windows VM to see if I can replicate.

**Comment by DonnC** [comment] 2020-08-25 12:38
And when i run `pub global activate fvm` again here are the dependecy list and versions
```
Package fvm is currently active at version 1.2.3.
Resolving dependencies...
+ args 1.6.0
+ charcode 1.1.3
+ cli_dialog 0.2.1
+ cli_util 0.2.0
+ collection 1.14.13
+ console 3.1.0
+ date_format 1.0.8
+ fvm 1.2.3
+ http 0.12.2
+ http_parser 3.1.4
+ io 0.3.4
+ meta 1.2.2
+ path 1.7.0
+ pedantic 1.9.2
+ process_run 0.10.12+2
+ pub_semver 1.4.4
+ source_span 1.7.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.2.0
+ vector_math 2.0.8
+ version 1.2.0
+ yaml 2.2.1
Precompiling executables...
Precompiled fvm:main.
Installed executable fvm.
Activated fvm 1.2.3.
```

**Comment by rydmike** [comment] 2020-08-26 03:11
Hi @DonnC another Flutter Windows user here. I had some issues installing fvm on Windows too, but got it running.

## Issues I ran into and how I solved them

#### 1. Old version of Dart SDK that is not supported by fvm installed interfered with the installation

I had an old version of Dart only SDK that was no longer supported by fvm in the path. The install tried using it before the newer one that is bundled with Flutter SDK, because it was earlier in the Windows environment path. Failed of course since the Dart SDK version was too old.

It probably does not matter for fvm if it uses an installed standalone Dart SDK or the one bundled with Flutter SDK, as long as the one it tries to use is a supported version. The one I had installed previously from pure dart coding was too old and not useful anymore for me either, so I removed it.

**It does not look like you have the above issue.** 
I just put it here in case somebody else would have an issue with the SDK version, as it threw me off at first. I knew my Dart SDK was one that was supported by fvm's range, yet it nagged it was too old and gave an old version, then I remembered ages ago I had installed plain vanilla Dart SDK. Flutter did not care, it worked happily with its own bundled one as it looks for it first in its own path, but **fvm** used the one the path env variable resolved to first, naturally.

#### 2. Installing with Windows Command Prompt

Installing fvm with Windows standard command prompt did not work for me at all "either". 

"Either" because I'm not sure if you used command prompt above or not, but based on the screenshots it looks like you might have. It did not help if I tried Windows command prompt with or without "Run as Administrator". The install with command:

`pub global activate fvm`

Seemed to work with command prompt, no major errors, but after the install even command 'fvm help' did not work.

I have VS-Code setup to use Windows Powershell as its terminal, it had been nagging me forever to:
"Try the new cross-platform PowerShell https://aka.ms/pscore6"

It's from Mircosoft and it is supposed to be more "developer friendly" as much more commands and scripts that work on Linux/Mac apparently should work on it as well. So I finally downloaded and installed it. With it installed fvm just started working as in the install instructions! Go figure, but it helped :smile: 

Maybe this will help you too, might be worth a try. I don't know if the Windows standard (older) powershell might have worked as well. I did not try with it, also not sure if you need to run the Windows cross-platform powershell as Administrator. I did though, but it might not even be needed.

#### 3. IDE instructions for Windows

After you get **fvm** up and running and have download maybe all channels and some specific versions you need, then the setup in IDE's on Windows are slightly different than described in the install guide, which I suspect works well on MacOS and Linux, but not directly as written on Windows.

## VS-Code on Windows
For VS-Code on Window the addition to the settings JSON needs to look like this:

```
{
  "dart.flutterSdkPaths": [ "C:\\Users\\username\\fvm\\versions"]
}
```
Mostly the difference is the format of the absolute path and that since Windows paths use backslash and that is control character in a JSON string, it needs to be there twice for every entry of it. Some apps on Windows also accept Linux/Mac forward "slash" formatted directory paths. Not sure if VS-Code does, I did not try since I had some other path entries in my VS-Code JSON settings file and they were all of the above format, so I just went with that.

In the path ` C:\\Users\\username\\fvm\\versions` of course refers to your fvm install path where all the Flutter SDK versions are downloaded. The above example path would be the most common default location on a Windows PC, where "username" of course refer to your windows username as used in a directory path.

After that it works as in the install instructions and you get a nice menu where you can select which SDK version to use.

## Studio or IntelliJ on Windows

The instructions: 
_Copy the absolute path of fvm symbolic link in your root project directory. Example: /absolute/path-to-your-project/.fvm/flutter_sdk_
Are not so helpful to Windows users. Long story short, in Studio/IntelliJ just go to
File -> Settings -> Languages & Framework -> Flutter:
Enter or copy/paste a path to one of your installed Flutter SDK versions:
![image](https://user-images.githubusercontent.com/39990307/91248305-06c88200-e75d-11ea-9483-2de9666ab303.png)

There is no automatic menu for all the installed version like in VS-Code (as far as I could see). So it is bit more tedious to change version in Studio/IntelliJ at first, but after you have entered a path once, for one of the installed versions, the IDE will remember previously used (available) ones and later you can switch by selecting one you have used before with the dropdown menu:

![image](https://user-images.githubusercontent.com/39990307/91248502-7a6a8f00-e75d-11ea-9f97-3f0c07a7680e.png)

---

That's it, hope any of this helps. It worked for my case, but hard to say if it will help with your case, there are always so many unknown scenarios and install conditions that can be different and fail. If it did help you and any of these instructions are useful for other Windows users, then @leoafarias et co are welcome to the clean them up and add them to the instructions if they like.

**Comment by leoafarias** [comment] 2020-08-29 01:00
@rydmike thanks for taking the time and putting this together. I will go through it and bring some of these items into the docs and see if there is anything to make the process easier on windows.

**Comment by rydmike** [comment] 2020-09-02 13:00
You are welcome @leoafarias 
BTW I tried again using the default Windows command prompt to use fvm, does not seem to work at all.
However, the default built in Windows Powershell does work, so you do not have to upgrade to the newer Powershell 7 from Microsoft to use fvm, like I did, if you don't want to. Just use the built in powershell instead of the widows command prompt and it all works OK.

A bit off topic, but I noticed that Max Weber @md-weber recently did a nice intro [video](https://www.youtube.com/watch?v=R6vKde1vIGQ) on using fvm on his YouTube channel "Flutter Explained". Maybe you saw it too. There are not so many tutorial videos out there on using fvm, maybe a link somewhere in the docs to his video could be a mutually beneficial collab? 😃

**Comment by leoafarias** [comment] 2020-09-02 13:24
@rydmike yes watched the video, and funny thing I actually asked him if I could exactly what you suggested.

I am working on better docs once I release the GUI app. 

Regarding windows it has been a bit tough to troubleshoot as my windows vm is not the average windows environment.

**Comment by devkarim** [comment] 2020-09-10 14:02
For anyone experiencing issues like ```Can't load Kernel binary: Invalid kernel binary format version```, just use ```pub global run fvm:main``` instead of using ```fvm``` so like when you want to use an SDK version in your project, use ```pub global run fvm:main use <version>```

You shouldn't see this error anymore afterward. I was experiencing this error for like an hour yesterday and suddenly it worked when I did the above command especially when I made usage of ```use``` command. Hope this helps!

**Comment by leoafarias** [comment] 2020-09-25 01:43
please test the latest prerelease version https://pub.dev/packages/fvm/versions/1.3.0-dev.0
`pub global activate fvm 1.3.0-dev.0` and report any issues

**Comment by leoafarias** [comment] 2020-09-25 17:01
closed in favor of #142

**Closed by leoafarias** 2020-09-25 17:01 UTC

**Comment by Byhuang1998** [comment] 2020-12-15 03:46
> closed in favor of #142

So is there an official solution? I have tried all the methods above but still cannot work.

**Comment by leoafarias** [comment] 2020-12-15 15:19
@Byhuang1998 The other thread gives some suggestions on how to troubleshoot, not sure if there is a particular open issue on Windows. If the steps in #142 do not solve, please open up a new issue and I will check it out.

**Comment by Greendogo** [comment] 2020-12-18 09:36
Before opening an issue, because I saw the GUI version advertised in several locations for Windows, I was assuming it was released in one of the last releases.  However, from my Windows fvm installation (1.3.4, I think), I'm having a hard time judging this to be true.

**Comment by leoafarias** [comment] 2020-12-18 15:25
@Greendogo The GUI is not part of the CLI. You can find it here. https://github.com/leoafarias/fvm/releases/tag/App-1.0.0-alpha.1

**Comment by Greendogo** [comment] 2020-12-18 22:49
> @Greendogo The GUI is not part of the CLI. You can find it here. https://github.com/leoafarias/fvm/releases/tag/App-1.0.0-alpha.1

Oh, thanks; it wasn't clear to me that it wasn't being included in the recent builds from the available ReadMe.  Do you think you could rebase this on something closer to Master?  No pressure if that's a pain :)

**Comment by leoafarias** [comment] 2020-12-18 22:57
I don't use windows daily so it's more if not being part of the workflow. 

I will try to do a release over the weekend.

In the meantime if you clone the rep. The App package you can run a build at any time. Just make sure you are on the dev channel
