### ISSUE TITLE
[BUG] FileSystemException: Cannot open file, path = 'C:\Users\claud\fvm\.settings'

### ISSUE THREAD

**Issue by ccastroelo** [leoafarias/fvm#372] opened 2021-11-19 22:03 UTC
Hello, 

Whenever I have a problem with the fvm I deactivate and activate it and it solves itself. Now I am without a solution. I'm on windows 11 and have developer mode enabled since windows 10. I've also tested doing everything as an administrator.

it seems to me that the problem is just this /fvm/.settings because enter as an administrator, I uninstalled fvm, reinstalled. I removed the 1.20.2 version of flutter I'm trying to work with, reinstalled it.. all no problem, but when I try to do something like fvm flutter pub get or compile, I get the .settings does not exist error.

************************************************************
If I run "pub cache repair" without fvm installed, it runs ok, if I run after "dart pub global activate fvm" I get:
************************************************************
Building package executables...
Failed to build fvm:main:
Error: Couldn't resolve the package 'fvm' in 'package:fvm/src/runner.dart'.
AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-2.2.4/bin/main.dart:3:8: Error: Not found: 'package:fvm/src/runner.dart'
import 'package:fvm/src/runner.dart';
       ^
AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-2.2.4/bin/main.dart:6:14: Error: Method not found: 'FvmCommandRunner'.
  exit(await FvmCommandRunner().run(args));
             ^^^^^^^^^^^^^^^^
Failed to reactivate fvm 2.2.4: Failed to build fvm:main:
Error: Couldn't resolve the package 'fvm' in 'package:fvm/src/runner.dart'.
AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-2.2.4/bin/main.dart:3:8: Error: Not found: 'package:fvm/src/runner.dart'
import 'package:fvm/src/runner.dart';
       ^
AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-2.2.4/bin/main.dart:6:14: Error: Method not found: 'FvmCommandRunner'.
  exit(await FvmCommandRunner().run(args));
             ^^^^^^^^^^^^^^^^
Binstubs exist for non-activated packages:
  From fvm: fvm
Reactivated 1 package.
Failed to reactivate 1 package:
- fvm

*************************
PS C:\Users\claud> fvm doctor
*************************
No FVM config found:
C:\Users\claud
Fvm will run the version in your PATH env: C:\src\flutter\bin\flutter.bat

Configured env paths:
___________________________________________________

Flutter:
C:\src\flutter\bin\flutter.bat

Dart:
C:\src\flutter\bin\dart.bat

FVM_HOME:
not set

And I'm getting the prints errors too.

![fvm](https://user-images.githubusercontent.com/2914324/142695602-e0c4ae81-9599-4dc5-8f53-783241904b04.png)

![fvm2](https://user-images.githubusercontent.com/2914324/142696877-9e61db76-ac63-431e-9469-95638f709ca0.png)

I appreciate any help, thanks.

Claudio

**Comment by ccastroelo** [comment] 2021-11-20 00:37
I got the contents of the .settings file from another issue I found.
{
"skipSetup": false,
"gitCache": false
}

Now when I run fvm flutter pub get I get:
*******************************************
C:\Users\claud\Desktop\flutter\apps\diarias>fvm --verbose flutter pub get
[     0.065s] Version: 1.20.2 - already installed.
[     0.082s] FileSystemException: Cannot create link to target 'C:\Users\claud\fvm\versions\1.20.2', path = 'C:\Users\claud\Desktop\flutter\apps\diarias\.fvm\flutter_sdk' (OS Error: Não é possível criar um arquivo já existente.
, errno = 183)
[     0.083s] Usage Exception: Seems you don't have the required permissions on C:\Users\claud\fvm On Windows FVM requires to run as an administrator or turn on developer mode: https://bit.ly/3vxRr2M

Could not install 1.20.2

Please run command with  --verbose if you want more information
************************************
even running cmd or windows power shell as administrator

**Comment by leoafarias** [comment] 2021-11-20 02:38
This seems to be a duplicate of this https://github.com/leoafarias/fvm/issues/352

The settings file is just a warning but it should not be the cause of what is happening.

**Closed** 2021-11-20 04:50 UTC
Labels: bug
