### ISSUE TITLE
[BUG] fvm can't find Java Runtime on Mac

### ISSUE THREAD

**Issue by TercyoStorck** [leoafarias/fvm#401] opened 2022-03-12 15:28 UTC
Hi,

I tried a lot to run an old project that run with flutter 1.22.6 on MacOS Monterey. I don't know if it is relecante but it's a mac with M1 chip.

All other projects that not using fvm, run without problem. But with fvm I get error message:

```
Launching lib[/main.dart]() on sdk gphone64 arm64 in debug mode...
lib/main.dart:1
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit [http://www.java.com]() for information on installing Java.

Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

Obs.: The same project is running on my linux with no problem.

**Comment by leoafarias** [comment] 2022-03-12 19:48
@TercyoStorck I might need a bit more info including the `fvm doctor` output. Could you confirm that running the same flutter version outside of FVM does work? If so I might need to know a bit more about your default `flutter` and `dart` path, together with the `flutter doctor` output

**Comment by iamsannyrai** [comment] 2022-03-15 03:41
@leoafarias  I got the same problem.

Here is screenshot for fvm flutter doctor --verbose.

<img width="712" alt="Screen Shot 2022-03-15 at 09 23 14" src="https://user-images.githubusercontent.com/50624619/158301545-d672d911-6fde-49ff-a86b-4acdb3c3568b.png">

However there is no problem on same command without fvm.

**Comment by iamsannyrai** [comment] 2022-03-16 15:49
@TercyoStorck Have you found any solution to this?

**Comment by leoafarias** [comment] 2022-03-16 16:05
@iamsannyrai based on the screenshot you are using 2 different versions of Flutter. I believe there was an issue they had to fix regarding this on newer SDKs.

Could you try calling directly the same version SDK, to see if you can reproduce the problem?

**Comment by leoafarias** [comment] 2022-03-16 16:44
@claudneysessa it seems that this is a flutter issue then.

**Comment by claudneysessa** [comment] 2022-03-17 02:34
I believe it is a fault related to the M1, because it works on windows... the problem is to know if we can wait for a solution or leave for another alternative.

<img width="835" alt="image" src="https://user-images.githubusercontent.com/12506432/158723134-4eabaec6-86f7-4dfd-b083-d30319f00001.png">

Send the data for analysis..
All on the same machine, running independently, removing dart and flutter before each test... But what I see that could be the problem is something related to android studio

Flutter Doctor 1.20.3

➜  testes flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on macOS 12.2.1 21D62, locale pt-BR)

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[!] Android Studio (version 2021.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.65.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
➜  testes

Flutter Doctor 2.2.2

➜  testes flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 12.2.1 21D62 darwin-arm, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2021.1)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.65.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
➜  testes

Flutter Doctor 2.5.0

➜  testes clear
➜  testes flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 12.2.1 21D62 darwin-arm, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.2)
[✓] Connected device (2 available)

• No issues found!
➜  testes

**Comment by leoafarias** [comment] 2022-03-17 03:01
@claudneysessa as mentioned it seems this was a flutter tooling issue that was resolved on a later versions of flutter as mentioned in the referenced issue

**Comment by iamsannyrai** [comment] 2022-03-17 03:16
@leoafarias Ya It might be the issue with m1 cause fvm is working well with the same version in my linux machine.

**Comment by leoafarias** [comment] 2022-03-21 23:53
Closing this ticket as it's related to an issue with an old flutter version

**Closed** 2022-03-21 23:53 UTC
Labels: bug
