### ISSUE TITLE
Internal Error: Could not install <stable>

### ISSUE THREAD

**Issue by ValeriusGC** [leoafarias/fvm#233] opened 2021-03-05 16:57 UTC
Hello!
I installed `dart`, then activated `fvm`.
`fvm releases` works well.
But `fvm install stable` raises error mentioned above.
--
Ubuntu 20.04 LTS
---
![Screenshot from 2021-03-05 21-59-11](https://user-images.githubusercontent.com/3320861/110148014-1f95ac80-7dfe-11eb-8dda-a8f3816bd886.png)

**Comment by ValeriusGC** [comment] 2021-03-05 17:20
Heh, works via install `flutter` and then `flutter pub global activate fvm` ))

**Comment by leoafarias** [comment] 2021-03-10 02:55
@ValeriusGC could you pass the --verbose flag?

**Comment by pavelDohnalik** [comment] 2021-03-13 13:30
Hello, I have the same issue.

**ubuntu 18.04 LTS**

![image](https://user-images.githubusercontent.com/17764174/111031588-950a0a00-8408-11eb-99bb-e201a6e9b0a6.png)

![image](https://user-images.githubusercontent.com/17764174/111031538-53795f00-8408-11eb-9e1e-f693dafff65e.png)

**Comment by ValeriusGC** [comment] 2021-03-21 03:17
> @ValeriusGC could you pass the --verbose flag?

I made this with workaround - installed entire flutter and then `fvm ..` from that.

**Comment by leoafarias** [comment] 2021-03-27 21:02
@ValeriusGC I am still curious to see what the issue was. The --verbose should be added on the 'fvm install stable' so it can show a stack trace.

I think this is a duplicate of this issue https://github.com/leoafarias/fvm/issues/213

**Comment by Hexagonale** [comment] 2021-04-03 10:25
Encountered this with fvm 1.3.8 on Windows 10 x64 today. 1.3.7 Works fine. Maybe related?

`Could not install <2.0.2>`
`#0      installWorkflow (package:fvm/src/workflows/install_version.workflow.dart:44:5)`
`<asynchronous suspension>`
`#1      FlutterCommand.run (package:fvm/src/commands/flutter_command.dart:30:7)`
`<asynchronous suspension>`
`#2      CommandRunner.runCommand (package:args/command_runner.dart:197:13)`
`<asynchronous suspension>`
`#3      FvmCommandRunner.run (package:fvm/src/runner.dart:60:14)`
`<asynchronous suspension>`
`#4      main (file:///C:/Users/Przemek/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fvm-1.3.8/bin/main.dart:4:3`
`<asynchronous suspension>`

**Comment by leoafarias** [comment] 2021-04-03 15:50
@Hexagonale can you run it with --verbose flag?

**Comment by Hexagonale** [comment] 2021-04-03 15:57
Ran as developer
`fvm --verbose flutter build apk --release`

`[     0.044s] FVM: Running version 2.0.2`
`[     0.057s] Exception: On Windows FVM requires to run in developer mode or as an administrator`
`Could not install <2.0.2>`
`#0      installWorkflow (package:fvm/src/workflows/install_version.workflow.dart:44:5)`
`<asynchronous suspension>`
`#1      FlutterCommand.run (package:fvm/src/commands/flutter_command.dart:30:7)`
`<asynchronous suspension>`
`#2      CommandRunner.runCommand (package:args/command_runner.dart:197:13)`
`<asynchronous suspension>`
`#3      FvmCommandRunner.run (package:fvm/src/runner.dart:60:14)`
`<asynchronous suspension>`
`#4      main (file:///C:/Users/Przemek/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fvm-1.3.8/bin/main.dart:4:3)`
`<asynchronous suspension>`

**Comment by leoafarias** [comment] 2021-04-03 16:31
@Hexagonale seems like it was not able to create the symlink which could still be permission.

Please download the lates fvm

pub global activate fvm 2.0.0-dev.4 

And run the same command with --verbose... it will output the exact error just to confirm that is permission.

**Comment by Hexagonale** [comment] 2021-04-03 16:35
All commands as administrator:
`pub global activate fvm 2.0.0-dev.4`
`Package fvm is currently active at version 1.3.8.`
`...`
`Activated fvm 2.0.0-dev.4.`

Confirm version:
`fvm --version`
`2.0.0-dev.4`

And it's working:
`fvm --verbose flutter build apk --release`
`[     0.330s] Version: 2.0.2 - already installed.`
`fvm: running version "2.0.2"`
` Building with sound null safety`
`Running Gradle task 'assembleRelease'...                           15,7s`
`√ Built build\app\outputs\flutter-apk\app-release.apk (19.6MB).`

**Comment by leoafarias** [comment] 2021-04-03 16:36
Great! I will go ahead and close this issue since the initial problem was for Ubuntu.

**Closed by leoafarias** 2021-04-03 16:36 UTC
Labels: bug

**Comment by oliverbytes** [comment] 2022-05-08 00:38
I'm getting the same error on Windows

**Comment by leoafarias** [comment] 2022-05-08 11:51
@oliverbytes please open up a new issue with the --verbose flag on the command and "fvm doctor"

**Comment by S-ecki** [comment] 2022-06-27 16:38
Commenting here for visibility: I had the same issue and fixed it by running my terminal as administrator. This is recommended by the `--verbose` tag already, but somehow the verbose tag did not produce this tip at the beginning.

**Comment by Abdelbasset193** [comment] 2023-09-24 21:20
please be sure to remove or rename the folder in your flutter project .vfm
then run vfm use ... 
or install again if not working
