### ISSUE TITLE
[BUG] Can't load Kernel binary: Invalid kernel binary format version.

### ISSUE THREAD

**Issue by disconnect5852** [leoafarias/fvm#333] opened 2021-07-16 08:57 UTC
**Describe the bug**
when i try to use fvm i get "Can't load Kernel binary: Invalid kernel binary format version."

**To Reproduce**

1. Go to terminal..
2. Run `fvm`...
3. Check...

**Expected behavior**
fvm to do anything.

**Logs**
PS C:\WINDOWS\system32> fvm --verbose
Can't load Kernel binary: Invalid kernel binary format version.
'pub' is not recognized as an internal or external command,
operable program or batch file.

**Desktop (please complete the following information):**

- OS: Windows 10 professional
- FVM Version 1.3.7
- If Windows: Windows powershell admin mode

**Additional context**
Yesterday i've installed and used it, today it isnt works anymore.

**Comment by leoafarias** [comment] 2021-07-16 11:55
@disconnect5852 I would update the local dart version if you are using... and follow the steps here https://fvm.app/docs/guides/faq#invalid-kernel-binary-or-invalid-sdk-hash-when-running-fvm

After trying the steps above, if it does not work please do a `fvm doctor`

**Comment by disconnect5852** [comment] 2021-07-16 12:49
As i wrote fvm itself does not work, nor with any arguments, so fvm doctor
neither works.

Leo Farias ***@***.***> ezt írta (időpont: 2021. júl. 16., P
13:55):

**Comment by leoafarias** [comment] 2021-07-16 14:31
@disconnect5852 understood. Please follow the instructions of the link I posted

**Comment by disconnect5852** [comment] 2021-07-16 15:36
does not solved. I've found it for the similar issue too, and tried that before posted this. Now i tried again, still not helps.

**Comment by leoafarias** [comment] 2021-07-16 16:45
@disconnect5852 some questions
- Were you using a global fvm version?
- Does the same happen if you install any other global pub.dev packages?

**Comment by leoafarias** [comment] 2021-07-16 21:22
For reference this is a duplicate of #100

**Closed** 2021-09-15 12:39 UTC
Labels: bug
