### ISSUE TITLE
Set Global Version doesn't work[BUG]

### ISSUE THREAD

**Issue by mengxy936** [leoafarias/fvm#200] opened 2020-12-22 03:04 UTC
**Describe the bug**
PS C:\Users\ke'j'f'l'da'j'h'l'f'\AndroidStudioProjects\state_app> fvm list
Versions path:  C:\Users\ke'j'f'l'da'j'h'l'f'\fvm\versions
1.17.1
1.24.0-10.2.pre ✔
v1.12.10 (global)
v1.9.1+hotfix.6

PS C:\Users\ke'j'f'l'da'j'h'l'f'\AndroidStudioProjects\state_app> fvm flutter --version
Flutter 1.24.0-10.2.pre • channel unknown • unknown source
Framework • revision 022b333a08 (5 weeks ago) • 2020-11-18 11:35:09 -0800
Engine • revision 07c1eed46b
Tools • Dart 2.12.0 (build 2.12.0-29.10.beta)

**Desktop (please complete the following information):**
 - OS: windows
 - FVM Version 1.2.3
 - If Windows: Which Powershell are you using? cmd

**Comment by leoafarias** [comment] 2020-12-22 20:18
Duplicate of #198

**Closed by leoafarias** 2020-12-22 20:18 UTC
Labels: bug
