### ISSUE TITLE
[Feature Request] "Symlinked" versions of stable, dev ... it should really link to their versioned directories

### ISSUE THREAD

**Issue by matecode** [leoafarias/fvm#341] opened 2021-09-09 11:48 UTC
Im using fvm since Flutter 2.2.3 came out. Now Flutter 2.5.0 is stable. I was wondering why "fvm install stable" was not installing version 2.5.0. I realized that stable is not a symlink to a version but an independent version. This undermines the usefulness of a version manager. 

**Is your feature request related to a problem? Please describe.**
If i link "stable" in my project, i would assume that if i run "fvm install stable" the most current stable version of flutter will be installed. instead stable stay on the version which it was initially installed, and you have to upgrade manually.

**Describe the solution you'd like**
"fvm install stable" creates a symlink to the directory of the current version, e.g. stable->2.2.3
if i run "fvm install stable" again and fvm recognizes that the new stable is 2.5.0, it changes the symlink to stable->2.5.0 and installs this version if its not already installed.

I hope i could cleary point out the issue. 
And of course: Thank you for your great work 🎉

**Comment by leoafarias** [comment] 2021-09-09 13:05
@matecode I believe this issue might be a duplicate of this https://github.com/leoafarias/fvm/issues/340 if it is, the problem should be resolved.

`fvm install stable` should indeed install the latest version on stable unless a previous stable version is already installed. In that case you would have to run a `fvm flutter upgrade`

**Comment by matecode** [comment] 2021-09-10 13:52
Thanks for your answer, but it isn't a duplicate as i have no problem with fvm, it is working correctly (as it should by design now). My suggestion is different. 

fvm should only install a symlink to to current stable version, but not install flutter in a directory called "stable". if i run "fvm install stable" again, it should check if the symlink is showing to the current stable version and if not, install the new stable version

this would habve the following advantages:
every flutter version is only installed in it named directory.
stable version stays stable without the need of "fvm flutter upgrade"

**Comment by leoafarias** [comment] 2021-09-10 16:58
@matecode I understand now. One thing that comes to mind though is the expectation of flutter behavior. When you install `stable` you are not installing the latest `stable` version, you are installing the stable channel. That is what people expect when using it. Changing this behavior might cause some confusion.

Regarding the benefit of not having to `fvm flutter upgrade,` you would still have to trigger an upgrade somehow, because upgrading in the background or automatically can definitely cause conflicting expectations.

**Comment by leoafarias** [comment] 2021-12-07 16:03
@matecode Take a look at the `--pin` flag described here. This might also solve your problem. I will go ahead and close this issue.

**Closed by leoafarias** 2021-12-07 16:03 UTC
Labels: enhancement
